# Generated by Django 6.0 on 2025-12-27 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0001_initial'),
        ('center', '0001_initial'),
        ('drug', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.center'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug.drug'),
        ),
        migrations.AddField(
            model_name='slot',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign'),
        ),
    ]
